# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build videorec
      run: cd videorec; go build -v ./...

    - name: Test videorec
      run: cd videorec; go test -v ./...

    - name: Build audiorec
      run: cd audiorec; go build -v ./...

    - name: Test audiorec
      run: cd audiorec; go test -v ./...

    - name: Build imagerec
      run: cd imagerec; go build -v ./...

    - name: Test imagerec
      run: cd imagerec; go test -v ./...